O4ZI.WebClient/Controllers/CommunityController.cs
using System.Web.Mvc;

namespace O4ZI.WebClient.Controllers
{
    public class CommunityController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

O4ZI.WebClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace O4ZI.WebClient.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

O4ZI.WebClient/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

O4ZI.WebClient/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "За нас";
}

@section Banner{ 
    <header>
        <h1>За нас</h1>
        <p>Къде и как можете да ни намерите</p>
    </header>
}
<article role="main" class="clearfix contact">
    <div class="post">
        <h2>О<sup>4</sup>ЗИ - Learning Network</h2>
        <p>Проект - дипломна работа на Гергана Георгиева</p>
        <p>фн:м23276</p>
        <p>специалност: Технологично предприемачество</p>
        <p>
            <span class="icon">[</span>: 0883 311 317<br />
            <span class="icon">M</span>: <a href="/mailto:dodstes@gmail.com">dodstes[at]gmail[dot]com</a>
        </p>
        <p>&nbsp;</p>
    </div>
    <div class="g-map"><img src="~/Content/images/map.png" alt="G Map" /></div>
</article>

@section Bottom{ 
    <footer class="foo-slogan">
        <form class="c-form">
            <h2>Остави ни съобщение ...</h2>
            <label for="name">Име</label>
            <input type="text" id="name">
            <label for="email">Имейл адрес</label>
            <input type="email" id="email">
            <label for="msg">Съобщение</label>
            <textarea id="msg" rows="10" cols="60"></textarea>
            <input type="submit" value="Изпрати" class="button green">
        </form>
    </footer>
}

O4ZI.WebClient/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Начало";
}

@section Banner{
    <header>
        <h1>Онлайн общество за обучение, обмяна на знания и идеи(О<sup>4</sup>ЗИ)</h1>
        <p>Можете да се свързвате със състудентите си, студентите си и приятелите си</p>
    </header>
}

<section class="container">
        <!-- // banner ends -->

        <article role="main" class="clearfix">
            <div class="post">
                <h2>Добре дошли на страниците на О<sup>4</sup>ЗИ</h2>
                <p>С навлизането на редицата социални мрежи в живота ни, вече не можем да си представим денят ни да минава без тях.</p>
                <p>Сайтът е интегриран с по-популярните от тях - <a href="https://www.facebook.com/">Facebook</a>, <a href="https://twitter.com/">Twitter</a>, <a href="http://www.youtube.com/">Youtube</a>.</p>
                <p>Част от възможностите на ООЗИ са:</p>
                <ul>
                    <li>Споделяне на лекции - текстови и видео формат</li>
                    <li>Споделяне на статии и интересна информация.</li>
                    <li>Оценяване на предоставените учебни материали.</li>
                </ul>
                <a href="@Url.Action("Index", "Community")" class="button left">Повече за нас<span class="icon">:</span></a>
            </div>
            <aside role="complementary">
                <a href="#demo-url"><img src="~/Content/images/community2.png" alt="Да учим заедно"></a>
            </aside>
        </article>
    </section>


@section Bottom{
    <div class="columns">
    <article>
        <figure>
            <img src="~/Content/images/Graduates~1.png" alt="Нови приятели">
            <figcaption>
                <h3>Нови приятели</h3>
                <p>Тук можете да срещнете както и настоящите си състуденти или студенти, така и <strong>нови съмишленици</strong>, с които да споделите своите идеи. <a href="/register" class="more-link">Регистрирай се сега &rarr;</a></p>
            </figcaption>
        </figure>
    </article>
    <article>
        <figure>
            <img src="~/Content/images/new_knowledge.png" alt="Нови знания" class="alt-col">
            <figcaption>
                <h3>Нови знания</h3>
                <p>Може да откриете <strong>много интересна информация</strong> по различните теми и предмети, много лекции, статии и видео материали. <a href="/register" class="more-link">Регистрирай се сега &rarr;</a></p>
            </figcaption>
        </figure>
    </article>
    <article>
        <figure>
            <img src="~/Content/images/new_fun2.png" alt="Нови забавления">
            <figcaption>
                <h3>Нови забавления</h3>
                <p>Можете да откриете, че има <strong>нови и забавни начини за учене</strong> и прекарване на времето пред компютъра, освен ровене из мрежата. <a href="/register" class="more-link">Регистрирай се сега &rarr;</a></p>
            </figcaption>
        </figure>
    </article>
    <article>
        <figure>
            <img src="~/Content/images/new_opportunities3.png" alt="Нови възможности" class="alt-col">
            <figcaption>
                <h3>Нови възможности</h3>
                <p>Тук можете да получите нови възможности да се занимавате с това, което искате, и да помагате на други да научат интересни неща. <a href="/register" class="more-link">Регистрирай се сега &rarr;</a></p>
            </figcaption>
        </figure>
    </article>
</div>
}